/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright © 2009, the Guru Online."
#property link      "http://www.theguruonline.biz"

#property indicator_chart_window

string gs_76 = "Pip tracker";
string gs_84 = "1.1";
extern int Display_Corner   = 3;
extern int Display_X_Offset = 260;
extern int Display_Y_Offset = 150;
extern string StartDate     = "yyyy.mm.dd hh:mm";
extern color Symbol_clr     = Goldenrod;
extern color Text_clr       = Black;
extern color Dn_clr         = FireBrick;
extern color Up_clr         = LimeGreen;
extern color Stats_clr      = DarkGray;
extern color BuyStats_clr   = LimeGreen;
extern color SellStats_clr  = FireBrick;

int gi_108;
bool gi_124;
int gi_unused_128 = 0;
int gi_132 = 1;

int init() {
   IndicatorShortName("Pip tracker");
   if (Digits == 3 || Digits == 5) gi_132 = 10 * gi_132;
   if (StartDate == "yyyy.mm.dd hh:mm") gi_108 = iTime(Symbol(), PERIOD_D1, 0);
   else gi_108 = StrToTime(StartDate);
   
   if (gi_132 == 1) _Draw_Label(Display_X_Offset + 74, Display_Y_Offset + 55, 13, "All " + Symbol() + " Trades", "0", Text_clr, "Tahoma", -1, 0);
   else _Draw_Label(Display_X_Offset + 74, Display_Y_Offset + 55, 13, "All " + Symbol() + " Trades", "0.0", Symbol_clr, "Tahoma", -1, 0);
   return (0);
}

int deinit() {
   string l_name_8;
   int l_objs_total_0 = ObjectsTotal();
   for (int l_objs_total_4 = l_objs_total_0; l_objs_total_4 >= 0; l_objs_total_4--) {
      l_name_8 = ObjectName(l_objs_total_4);
      if (StringSubstr(l_name_8, 0, StringLen(gs_76) + 2) == "[" + gs_76 + "]") ObjectDelete(l_name_8);
   }
   return (0);
}

int start() {
   int li_28;
   bool li_68;
   gi_124 = FALSE;
  
   _Draw_Label(Display_X_Offset + 44, Display_Y_Offset + 145, 12, Symbol(), Symbol(), Symbol_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 38, Display_Y_Offset + 93, 8, "Trades Since1", "|", Stats_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 104, Display_Y_Offset + 93, 8, "Trades Since2", "|", Stats_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 38, Display_Y_Offset + 83, 8, "Trades Since3", "|", Stats_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 104, Display_Y_Offset + 83, 8, "Trades Since4", "|", Stats_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 32, Display_Y_Offset + 75, 10, "Separator", "____________","Tahoma",Gray);
   _Draw_Label(Display_X_Offset + 45, Display_Y_Offset + 82, 8, "Start Date", TimeToStr(gi_108,TIME_DATE), Stats_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 46, Display_Y_Offset + 94, 8, "Stats since", "stats since", Stats_clr, "Tahoma", -1, 0);
   
   
   double ld_0 = 0;
   double ld_8 = 0;
   double ld_16 = 0;
   int l_count_32 = 0;
   int l_count_36 = 0;
   int l_count_40 = 0;
   int l_count_44 = 0;
   int l_count_48 = 0;
   int l_count_52 = 0;
   int l_count_56 = 0;
   int l_count_60 = 0;
   int l_color_64 = Text_clr;
   if (OrdersTotal() != 0) {
      li_68 = FALSE;
      for (int l_pos_24 = 0; l_pos_24 < OrdersTotal(); l_pos_24++) {
         li_28 = 1;
         if (OrderSelect(l_pos_24, SELECT_BY_POS, MODE_TRADES) == FALSE) {
            Print("Access to orders failed with error (", GetLastError(), ")");
            break;
         }
         if (MarketInfo(OrderSymbol(), MODE_DIGITS) == 3.0 || MarketInfo(OrderSymbol(), MODE_DIGITS) == 5.0) li_28 = 10;
         if (OrderType() == OP_BUY && OrderOpenTime() >= gi_108) {
            l_count_36++;
            if (OrderProfit() >= 0.0) l_count_44++;
            ld_8 += (OrderClosePrice() - OrderOpenPrice()) / MarketInfo(OrderSymbol(), MODE_POINT) / li_28;
            if (OrderSymbol() == Symbol()) {
               l_count_32++;
               if (OrderProfit() >= 0.0) l_count_40++;
               li_68 = TRUE;
               ld_16 += OrderLots();
               ld_0 += (OrderClosePrice() - OrderOpenPrice()) / MarketInfo(OrderSymbol(), MODE_POINT) / li_28;
            }
         } else {
            if (OrderType() == OP_SELL && OrderOpenTime() >= gi_108) {
               l_count_52++;
               if (OrderProfit() >= 0.0) l_count_60++;
               ld_8 += (OrderOpenPrice() - OrderClosePrice()) / MarketInfo(OrderSymbol(), MODE_POINT) / li_28;
               if (OrderSymbol() == Symbol()) {
                  l_count_48++;
                  if (OrderProfit() >= 0.0) l_count_56++;
                  li_68 = TRUE;
                  ld_16 -= OrderLots();
                  ld_0 += (OrderOpenPrice() - OrderClosePrice()) / MarketInfo(OrderSymbol(), MODE_POINT) / li_28;
               }
            }
         }
      }
   }
   
   if (OrdersHistoryTotal() != 0) {
      for (l_pos_24 = 0; l_pos_24 < OrdersHistoryTotal(); l_pos_24++) {
         li_28 = 1;
         if (OrderSelect(l_pos_24, SELECT_BY_POS, MODE_HISTORY) == FALSE) {
            Print("Access to orders failed with error (", GetLastError(), ")");
            break;
         }
         if (MarketInfo(OrderSymbol(), MODE_DIGITS) == 3.0 || MarketInfo(OrderSymbol(), MODE_DIGITS) == 5.0) li_28 = 10;
         if (OrderType() == OP_BUY && OrderOpenTime() >= gi_108) {
            l_count_36++;
            if (OrderProfit() >= 0.0) l_count_44++;
            ld_8 += (OrderClosePrice() - OrderOpenPrice()) / MarketInfo(OrderSymbol(), MODE_POINT) / li_28;
            if (OrderSymbol() == Symbol()) {
               l_count_32++;
               if (OrderProfit() >= 0.0) l_count_40++;
               ld_0 += (OrderClosePrice() - OrderOpenPrice()) / MarketInfo(OrderSymbol(), MODE_POINT) / li_28;
            }
         } else {
            if (OrderType() == OP_SELL && OrderOpenTime() >= gi_108) {
               l_count_52++;
               if (OrderProfit() >= 0.0) l_count_60++;
               ld_8 += (OrderOpenPrice() - OrderClosePrice()) / MarketInfo(OrderSymbol(), MODE_POINT) / li_28;
               if (OrderSymbol() == Symbol()) {
                  l_count_48++;
                  if (OrderProfit() >= 0.0) l_count_56++;
                  ld_0 += (OrderOpenPrice() - OrderClosePrice()) / MarketInfo(OrderSymbol(), MODE_POINT) / li_28;
               }
            }
         }
      }
      l_color_64 = Text_clr;
     
      if (ld_0 > 0.0) l_color_64 = Up_clr;
      else
         if (ld_0 < 0.0) l_color_64 = Dn_clr;
      if (gi_132 == 1) _Draw_Label(Display_X_Offset + 80, Display_Y_Offset + 55, 12, "All " + Symbol() + " Trades", DoubleToStr(ld_0, 0), l_color_64, "Tahoma", -1, 0);
      else _Draw_Label(Display_X_Offset + 74, Display_Y_Offset + 55, 12, "All " + Symbol() + " Trades", DoubleToStr(ld_0, 1), l_color_64, "Tahoma", -1, 0);
   }
      
   _Draw_Label(Display_X_Offset + 45, Display_Y_Offset + 111, 8, "Long", "Long", Text_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 80, Display_Y_Offset + 111, 8, "Buy Wins", l_count_40 + "/" + l_count_32, BuyStats_clr, "Tahoma", -1, 0);   
   _Draw_Label(Display_X_Offset + 43, Display_Y_Offset + 125, 8, "Short", "Short", Text_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 80, Display_Y_Offset + 125, 8, "Sell Wins", l_count_56 + "/" + l_count_48, SellStats_clr, "Tahoma", -1, 0);
   _Draw_Label(Display_X_Offset + 37, Display_Y_Offset + 56,  11, "Pips", "Pips", Text_clr, "Tahoma", -1, 0);
   
   return (0);
}

void _Draw_Label(int a_x_0, int a_y_4, int a_fontsize_8, string as_12, string a_text_20, color a_color_28, string a_fontname_32, int a_corner_40 = -1, int a_window_44 = -1) {
   if (a_corner_40 == -1) a_corner_40 = Display_Corner;
   if (a_window_44 == -1) a_window_44 = gi_124;
   ObjectDelete("[" + gs_76 + "] " + as_12);
   ObjectCreate("[" + gs_76 + "] " + as_12, OBJ_LABEL, a_window_44, 0, 0);
   ObjectSetText("[" + gs_76 + "] " + as_12, a_text_20, a_fontsize_8, a_fontname_32, a_color_28);
   ObjectSet("[" + gs_76 + "] " + as_12, OBJPROP_BACK, TRUE);
   ObjectSet("[" + gs_76 + "] " + as_12, OBJPROP_CORNER, a_corner_40);
   ObjectSet("[" + gs_76 + "] " + as_12, OBJPROP_XDISTANCE, a_x_0);
   ObjectSet("[" + gs_76 + "] " + as_12, OBJPROP_YDISTANCE, a_y_4);
}