/*
   Generated by ex4-to-mq4 decompiler FREEWARE 4.0.451.5
   Website:  h t T P :/ / w w w .Me t aQ uO TE s.n e T
   E-mail :  S u pP O R T @Me TaQu OT E s . Net
*/
#property copyright "Copyright © 2008, FOREXflash Software Corp."
#property link      "http://www.metaquotes.net"

#property indicator_chart_window
#property indicator_buffers 3
#property indicator_color1 White
#property indicator_color2 DeepSkyBlue
#property indicator_color3 Orange

int Gi_unused_76 = 500;
double G_ibuf_80[];
double G_ibuf_84[];
double G_ibuf_88[];
string Gs_unused_92;

int init() {
   string Ls_0 = "2009.06.12";
   int str2time_8 = StrToTime(Ls_0);
   if (TimeCurrent() >= str2time_8) {
      Alert("The trial version expired! Contact forexflash@gmail.com");
      return (1);
   }
   SetIndexBuffer(0, G_ibuf_80);
   SetIndexStyle(0, DRAW_ARROW);
   SetIndexArrow(0, 159);
   SetIndexLabel(0, "MIDDLE OF BAR");
   SetIndexBuffer(1, G_ibuf_84);
   SetIndexStyle(1, DRAW_ARROW);
   SetIndexArrow(1, 161);
   SetIndexLabel(1, "UPPER PART OF BAR");
   SetIndexBuffer(2, G_ibuf_88);
   SetIndexStyle(2, DRAW_ARROW);
   SetIndexArrow(2, 161);
   SetIndexLabel(2, "LOWER PART OF BAR");
   string Ls_12 = "VSA© BAR DOTS";
   IndicatorShortName(Ls_12);
   Gs_unused_92 = Ls_12;
   IndicatorDigits(1);
   return (1);
}

int deinit() {
   return (0);
}

int start() {
   double Ld_12;
   double Ld_20;
   double Ld_28;
   int Li_8 = IndicatorCounted();
   if (Li_8 > 0) Li_8--;
   int Li_4 = Bars - Li_8;
   for (int count_0 = 0; count_0 < Li_4; count_0++) {
      Ld_12 = (High[count_0 + 1] + (Low[count_0 + 1])) / 2.0;
      Ld_20 = (High[count_0 + 1] + (Low[count_0 + 1])) / 2.0 + (High[count_0 + 1] - (Low[count_0 + 1])) / 3.6;
      Ld_28 = (High[count_0 + 1] + (Low[count_0 + 1])) / 2.0 - (High[count_0 + 1] - (Low[count_0 + 1])) / 3.6;
      if (Close[count_0 + 1] < Ld_20 && Close[count_0 + 1] > Ld_28) G_ibuf_80[count_0 + 1] = Ld_12;
      if (Close[count_0 + 1] > Ld_20) G_ibuf_84[count_0 + 1] = Ld_20;
      if (Close[count_0 + 1] < Ld_28) G_ibuf_88[count_0 + 1] = Ld_28;
   }
   return (0);
}
