/*
   Generated by EX4-TO-MQ4 decompiler V4.0.223.1a []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright © 2008, FOREXflash Software Corp."
#property link      "http://www.metaquotes.net"

#property indicator_separate_window
#property indicator_buffers 7
#property indicator_color1 White
#property indicator_color2 Lime
#property indicator_color3 Red
#property indicator_color4 Black
#property indicator_color5 Gray
#property indicator_color6 Red
#property indicator_color7 Lime

extern bool ShowText = TRUE;
extern int Corner = 1;
extern int MA_Length = 100;
double g_ibuf_88[];
double g_ibuf_92[];
double g_ibuf_96[];
double g_ibuf_100[];
double g_ibuf_104[];
double g_ibuf_108[];
double g_ibuf_112[];
int gi_116 = 1;
string gs_120;

int init() {
   /*string ls_0 = "2009.07.06";
   int l_str2time_8 = StrToTime(ls_0);
   if (TimeCurrent() >= l_str2time_8) {
      Alert("The trial version expired! Contact forexflash@gmail.com");
      return (1);
   }*/
   SetIndexBuffer(0, g_ibuf_88);
   SetIndexStyle(0, DRAW_HISTOGRAM);
   SetIndexLabel(0, "Spread(High-Low)");
   SetIndexStyle(1, DRAW_HISTOGRAM);
   SetIndexBuffer(1, g_ibuf_92);
   SetIndexLabel(1, "UpperWick");
   SetIndexStyle(2, DRAW_HISTOGRAM);
   SetIndexBuffer(2, g_ibuf_96);
   SetIndexLabel(2, "LowerWick");
   SetIndexBuffer(3, g_ibuf_100);
   SetIndexStyle(3, DRAW_NONE);
   SetIndexBuffer(4, g_ibuf_104);
   SetIndexStyle(4, DRAW_LINE, STYLE_DOT);
   SetIndexLabel(4, "AvgVolumes");
   SetIndexBuffer(5, g_ibuf_108);
   SetIndexStyle(5, DRAW_ARROW, STYLE_SOLID);
   SetIndexArrow(5, 159);
   SetIndexBuffer(6, g_ibuf_112);
   SetIndexStyle(6, DRAW_ARROW, STYLE_SOLID);
   SetIndexArrow(6, 159);
   string ls_12 = "VSA© Spread&WickHistogram";
   IndicatorShortName(ls_12);
   gs_120 = ls_12;
   ObjectDelete("Spread(High-Low)");
   IndicatorDigits(1);
   return (1);
}

int deinit() {
   ObjectDelete("Market_Price_Label");
   ObjectsDeleteAll(0, OBJ_LABEL);
   ObjectsDeleteAll();
   return (0);
}

int start() {
   double ld_16;
   double ld_24;
   double ld_32;
   if (ShowText == TRUE) draw_objects();
   AVGVolume();
   BST();
   int li_8 = IndicatorCounted();
   if (li_8 < 0) return (-1);
   if (li_8 > 0) li_8--;
   for (int li_12 = Bars - li_8; li_12 >= 0; li_12--) {
      ld_16 = iHigh(NULL, 0, li_12) - iLow(NULL, 0, li_12);
      g_ibuf_88[li_12] = ld_16 / Point / gi_116;
      if (iOpen(NULL, 0, li_12) > iClose(NULL, 0, li_12)) ld_24 = iHigh(NULL, 0, li_12) - iOpen(NULL, 0, li_12);
      if (iOpen(NULL, 0, li_12) <= iClose(NULL, 0, li_12)) ld_24 = iHigh(NULL, 0, li_12) - iClose(NULL, 0, li_12);
      if (iOpen(NULL, 0, li_12) > iClose(NULL, 0, li_12)) ld_32 = iLow(NULL, 0, li_12) - iClose(NULL, 0, li_12);
      if (iOpen(NULL, 0, li_12) <= iClose(NULL, 0, li_12)) ld_32 = iLow(NULL, 0, li_12) - iOpen(NULL, 0, li_12);
      g_ibuf_92[li_12] = ld_24 / Point / gi_116;
      g_ibuf_96[li_12] = ld_32 / Point / gi_116;
   }
   return (0);
}

int AVGVolume() {
   int li_8 = IndicatorCounted();
   if (li_8 > 0) li_8--;
   int li_4 = Bars - li_8;
   for (int li_0 = 0; li_0 < li_4; li_0++) g_ibuf_100[li_0] = (iHigh(NULL, 0, li_0) - iLow(NULL, 0, li_0)) / Point / gi_116;
   for (li_0 = 0; li_0 < li_4; li_0++) g_ibuf_104[li_0] = iMAOnArray(g_ibuf_100, 0, MA_Length, 0, MODE_EMA, li_0);
   return (0);
}

void BST() {
   for (int l_index_0 = 0; l_index_0 < 500; l_index_0++) {
      if (Open[l_index_0] < Close[l_index_0]) g_ibuf_112[l_index_0] = g_ibuf_88[l_index_0] + 1.0;
      if (Close[l_index_0] < Open[l_index_0]) g_ibuf_108[l_index_0] = g_ibuf_88[l_index_0] + 1.0;
   }
}

void draw_objects() {
   ObjectCreate("Box", OBJ_LABEL, WindowFind(gs_120), 0, 0);
   ObjectSetText("Box", "V  S  A  ®", 14, "Trebuchet MS", Orange);
   ObjectSet("Box", OBJPROP_CORNER, Corner);
   ObjectSet("Box", OBJPROP_XDISTANCE, 15);
   ObjectSet("Box", OBJPROP_YDISTANCE, 1);
   ObjectCreate("Box1", OBJ_LABEL, WindowFind(gs_120), 0, 0);
   ObjectSetText("Box1", "Spread/Wick/Candle", 8, "Trebuchet MS", Gray);
   ObjectSet("Box1", OBJPROP_CORNER, Corner);
   ObjectSet("Box1", OBJPROP_XDISTANCE, 15);
   ObjectSet("Box1", OBJPROP_YDISTANCE, 18);
   string l_dbl2str_0 = DoubleToStr(g_ibuf_88[0], 1);
   ObjectCreate("Spread(High-Low)", OBJ_LABEL, WindowFind(gs_120), 0, 0);
   ObjectSetText("Spread(High-Low)", "Spread(H-L):" + l_dbl2str_0, 13, "Trebuchet MS", White);
   ObjectSet("Spread(High-Low)", OBJPROP_CORNER, Corner);
   ObjectSet("Spread(High-Low)", OBJPROP_XDISTANCE, 15);
   ObjectSet("Spread(High-Low)", OBJPROP_YDISTANCE, 34);
   ObjectCreate("BA_Spread(High-Low)", OBJ_LABEL, WindowFind(gs_120), 0, 0);
   ObjectSetText("BA_Spread(High-Low)", "SPREAD IS BELOW AVERAGE.", 8, "Trebuchet MS", White);
   ObjectSet("BA_Spread(High-Low)", OBJPROP_CORNER, Corner);
   ObjectSet("BA_Spread(High-Low)", OBJPROP_XDISTANCE, 15);
   ObjectSet("BA_Spread(High-Low)", OBJPROP_YDISTANCE, 54);
   if (g_ibuf_88[0] > g_ibuf_104[0]) ObjectSetText("BA_Spread(High-Low)", "SPREAD IS ABOVE AVERAGE!!!", 8, "Trebuchet MS", Red);
   string l_dbl2str_8 = DoubleToStr(g_ibuf_92[0], 1);
   ObjectCreate("UpWick", OBJ_LABEL, WindowFind(gs_120), 0, 0);
   ObjectSetText("UpWick", "Upper Wick:" + l_dbl2str_8, 13, "Trebuchet MS", Lime);
   ObjectSet("UpWick", OBJPROP_CORNER, Corner);
   ObjectSet("UpWick", OBJPROP_XDISTANCE, 15);
   ObjectSet("UpWick", OBJPROP_YDISTANCE, 66);
   ObjectCreate("BA_UpWick", OBJ_LABEL, WindowFind(gs_120), 0, 0);
   ObjectSetText("BA_UpWick", "UpWICK IS BELOW AVERAGE.", 8, "Trebuchet MS", White);
   ObjectSet("BA_UpWick", OBJPROP_CORNER, Corner);
   ObjectSet("BA_UpWick", OBJPROP_XDISTANCE, 15);
   ObjectSet("BA_UpWick", OBJPROP_YDISTANCE, 86);
   if (g_ibuf_92[0] > g_ibuf_92[1] && g_ibuf_92[0] > g_ibuf_92[2] && g_ibuf_92[0] > g_ibuf_92[3] && g_ibuf_92[0] > g_ibuf_92[4] && g_ibuf_92[0] > g_ibuf_92[5] && g_ibuf_92[0] > g_ibuf_92[6] &&
      g_ibuf_92[0] > g_ibuf_92[7] && g_ibuf_92[0] > g_ibuf_92[8] && g_ibuf_92[0] > g_ibuf_92[9] && g_ibuf_92[0] > g_ibuf_92[10] && g_ibuf_92[0] > g_ibuf_92[11] && g_ibuf_92[0] > g_ibuf_92[12] &&
      g_ibuf_92[0] > g_ibuf_92[13] && g_ibuf_92[0] > g_ibuf_92[14] && g_ibuf_92[0] > g_ibuf_92[15] && g_ibuf_92[0] > g_ibuf_92[16] && g_ibuf_92[0] > g_ibuf_92[17] && g_ibuf_92[0] > g_ibuf_92[18] &&
      g_ibuf_92[0] > g_ibuf_92[19] && g_ibuf_92[0] > g_ibuf_92[20]) ObjectSetText("BA_UpWick", "UpWICK IS ABOVE AVERAGE!!!", 8, "Trebuchet MS", Lime);
   string l_dbl2str_16 = DoubleToStr(g_ibuf_96[0], 1);
   ObjectCreate("DnWick", OBJ_LABEL, WindowFind(gs_120), 0, 0);
   ObjectSetText("DnWick", "Lower Wick:" + l_dbl2str_16, 13, "Trebuchet MS", Red);
   ObjectSet("DnWick", OBJPROP_CORNER, Corner);
   ObjectSet("DnWick", OBJPROP_XDISTANCE, 15);
   ObjectSet("DnWick", OBJPROP_YDISTANCE, 98);
   ObjectCreate("DN_UpWick", OBJ_LABEL, WindowFind(gs_120), 0, 0);
   ObjectSetText("DN_UpWick", "DnWICK IS BELOW AVERAGE.", 8, "Trebuchet MS", White);
   ObjectSet("DN_UpWick", OBJPROP_CORNER, Corner);
   ObjectSet("DN_UpWick", OBJPROP_XDISTANCE, 15);
   ObjectSet("DN_UpWick", OBJPROP_YDISTANCE, 116);
   if (g_ibuf_96[0] > g_ibuf_96[1] && g_ibuf_96[0] > g_ibuf_96[2] && g_ibuf_96[0] > g_ibuf_96[3] && g_ibuf_96[0] > g_ibuf_96[4] && g_ibuf_96[0] > g_ibuf_96[5] && g_ibuf_96[0] > g_ibuf_96[6] &&
      g_ibuf_96[0] > g_ibuf_96[7] && g_ibuf_96[0] > g_ibuf_96[8] && g_ibuf_96[0] > g_ibuf_96[9] && g_ibuf_96[0] > g_ibuf_96[10] && g_ibuf_96[0] > g_ibuf_96[11] && g_ibuf_96[0] > g_ibuf_96[12] &&
      g_ibuf_96[0] > g_ibuf_96[13] && g_ibuf_96[0] > g_ibuf_96[14] && g_ibuf_96[0] > g_ibuf_96[15] && g_ibuf_96[0] > g_ibuf_96[16] && g_ibuf_96[0] > g_ibuf_96[17] && g_ibuf_96[0] > g_ibuf_96[18] &&
      g_ibuf_96[0] > g_ibuf_96[19] && g_ibuf_96[0] > g_ibuf_96[20]) ObjectSetText("DN_UpWick", "DnWICK IS ABOVE AVERAGE!!!", 8, "Trebuchet MS", Red);
}