/*
   Generated by EX4-TO-MQ4 decompiler V4.0.223.1a []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright © 2008, FOREXflash Software Corp."
#property link      "http://www.metaquotes.net"

#property indicator_chart_window
#property indicator_buffers 7
#property indicator_color1 Black
#property indicator_color2 Black
#property indicator_color3 Black
#property indicator_color4 Black
#property indicator_color5 Black
#property indicator_color6 Black
#property indicator_color7 Black

extern bool ShowText = TRUE;
extern int MA_Length = 100;
double g_ibuf_84[];
double g_ibuf_88[];
double g_ibuf_92[];
double g_ibuf_96[];
double g_ibuf_100[];
double g_ibuf_104[];
double g_ibuf_108[];
int gi_112 = 1;
string gs_unused_116;
int gi_124 = 500;

int init() {
   /*string ls_0 = "2009.07.06";
   int l_str2time_8 = StrToTime(ls_0);
   if (TimeCurrent() >= l_str2time_8) {
      Alert("The trial version expired! Contact forexflash@gmail.com");
      return (1);
   }*/
   SetIndexBuffer(0, g_ibuf_84);
   SetIndexStyle(0, DRAW_NONE);
   SetIndexBuffer(1, g_ibuf_88);
   SetIndexStyle(1, DRAW_NONE);
   SetIndexBuffer(2, g_ibuf_92);
   SetIndexStyle(2, DRAW_NONE);
   SetIndexBuffer(3, g_ibuf_96);
   SetIndexStyle(3, DRAW_NONE);
   SetIndexBuffer(4, g_ibuf_100);
   SetIndexStyle(4, DRAW_NONE);
   SetIndexBuffer(5, g_ibuf_104);
   SetIndexStyle(5, DRAW_NONE);
   SetIndexBuffer(6, g_ibuf_108);
   SetIndexStyle(6, DRAW_NONE);
   string ls_12 = "VSA© Spread&WickHistogram";
   IndicatorShortName(ls_12);
   gs_unused_116 = ls_12;
   ObjectDelete("Spread(High-Low)");
   IndicatorDigits(1);
   return (1);
}

int deinit() {
   ObjectDelete("Market_Price_Label");
   ObjectsDeleteAll(0, OBJ_LABEL);
   ObjectsDeleteAll();
   return (0);
}

int start() {
   double ld_16;
   if (ShowText == TRUE) draw_objects();
   AVGSpread();
   AVGVolume();
   int li_8 = IndicatorCounted();
   if (li_8 < 0) return (-1);
   if (li_8 > 0) li_8--;
   for (int li_12 = Bars - li_8; li_12 >= 0; li_12--) {
      ld_16 = iHigh(NULL, 0, li_12) - iLow(NULL, 0, li_12);
      g_ibuf_84[li_12] = ld_16 / Point / gi_112;
   }
   return (0);
}

int AVGSpread() {
   int li_8 = IndicatorCounted();
   if (li_8 > 0) li_8--;
   int li_4 = Bars - li_8;
   for (int li_0 = 0; li_0 < li_4; li_0++) g_ibuf_88[li_0] = (iHigh(NULL, 0, li_0) - iLow(NULL, 0, li_0)) / Point / gi_112;
   for (li_0 = 0; li_0 < li_4; li_0++) g_ibuf_92[li_0] = iMAOnArray(g_ibuf_88, 0, MA_Length, 0, MODE_EMA, li_0);
   return (0);
}

int AVGVolume() {
   double ld_0;
   int li_12 = IndicatorCounted();
   if (li_12 > 0) li_12--;
   if (gi_124 == 0) gi_124 = Bars - li_12;
   int li_8 = gi_124;
   for (int li_16 = 0; li_16 < li_8; li_16++) {
      ld_0 = 0;
      for (int li_20 = li_16; li_20 < li_16 + MA_Length; li_20++) ld_0 = Volume[li_20] + ld_0;
      g_ibuf_104[li_16] = NormalizeDouble(ld_0 / MA_Length, 0);
      g_ibuf_108[li_16] = iVolume(NULL, 0, li_16);
   }
   return (0);
}

void draw_objects() {
   if (ObjectFind("000") == -1) {
      ObjectCreate("000", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("000", "~", 20, "Webdings", Red);
      ObjectSet("000", OBJPROP_CORNER, 3);
      ObjectSet("000", OBJPROP_XDISTANCE, 58);
      ObjectSet("000", OBJPROP_YDISTANCE, 1);
   }
   if (ObjectFind("111") == -1) {
      ObjectCreate("111", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("111", "FOREXflash", 8, "Tahoma", White);
      ObjectSet("111", OBJPROP_CORNER, 3);
      ObjectSet("111", OBJPROP_XDISTANCE, 15);
      ObjectSet("111", OBJPROP_YDISTANCE, 8);
   }
   if (ObjectFind("sig2b") == -1) {
      ObjectCreate("sig2bD", OBJ_LABEL, 0, 0, 0);
      ObjectSet("sig2bD", OBJPROP_COLOR, Red);
      ObjectSet("sig2bD", OBJPROP_XDISTANCE, 5);
      ObjectSet("sig2bD", OBJPROP_YDISTANCE, 20);
   }
   ObjectSetText("sig2bD", "VOLUME: PENDING..", 10, "Tahoma Bold", White);
   if (g_ibuf_108[1] > g_ibuf_104[1]) ObjectSetText("sig2bD", "VOLUME: HIGH", 10, "Tahoma Bold", Lime);
   if (g_ibuf_108[1] < g_ibuf_104[1]) ObjectSetText("sig2bD", "VOLUME: LOW ", 10, "Tahoma Bold", Red);
   if (g_ibuf_108[1] > 2.0 * g_ibuf_104[1]) ObjectSetText("sig2bD", "VOLUME: VERY HIGH", 10, "Tahoma Bold", Lime);
   if (g_ibuf_108[1] < g_ibuf_104[1] / 2.0) ObjectSetText("sig2bD", "VOLUME: VERY LOW ", 10, "Tahoma Bold", Red);
   if (ObjectFind("sig") == -1) {
      ObjectCreate("sig", OBJ_LABEL, 0, 0, 0);
      ObjectSet("sig", OBJPROP_COLOR, Red);
      ObjectSet("sig", OBJPROP_XDISTANCE, 140);
      ObjectSet("sig", OBJPROP_YDISTANCE, 20);
   }
   ObjectSetText("sig", "SPREAD: MEDIUM", 10, "Tahoma Bold", White);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1]) ObjectSetText("sig", "SPREAD: WIDE", 10, "Tahoma Bold", Orange);
   if (g_ibuf_84[1] < g_ibuf_92[1] / 2.0) ObjectSetText("sig", "SPREAD: NARROW", 10, "Tahoma Bold", White);
   if (ObjectFind("sig2") == -1) {
      ObjectCreate("sig2", OBJ_LABEL, 0, 0, 0);
      ObjectSet("sig2", OBJPROP_COLOR, Red);
      ObjectSet("sig2", OBJPROP_XDISTANCE, 260);
      ObjectSet("sig2", OBJPROP_YDISTANCE, 20);
   }
   ObjectSetText("sig2", "BAR POS:PENDING..", 10, "Tahoma Bold", White);
   if (Close[1] > Close[2]) ObjectSetText("sig2", "BAR POS: UPBAR", 10, "Tahoma Bold", Lime);
   if (Close[1] < Close[2]) ObjectSetText("sig2", "BAR POS: DNBAR", 10, "Tahoma Bold", Red);
   double ld_0 = (High[1] + Low[1]) / 2.0;
   double ld_8 = (High[1] + Low[1]) / 2.0 + (High[1] - Low[1]) / 3.0;
   double ld_16 = (High[1] + Low[1]) / 2.0 - (High[1] - Low[1]) / 3.0;
   if (ObjectFind("sig2a") == -1) {
      ObjectCreate("sig2a", OBJ_LABEL, 0, 0, 0);
      ObjectSet("sig2a", OBJPROP_COLOR, Red);
      ObjectSet("sig2a", OBJPROP_XDISTANCE, 380);
      ObjectSet("sig2a", OBJPROP_YDISTANCE, 20);
   }
   ObjectSetText("sig2a", "BAR CLOSE: MIDCLOSE", 10, "Tahoma Bold", White);
   if (Close[1] > ld_8) ObjectSetText("sig2a", "BAR CLOSE: UPCLOSE", 10, "Tahoma Bold", Lime);
   if (Close[1] < ld_16) ObjectSetText("sig2a", "BAR CLOSE: DNCLOSE", 10, "Tahoma Bold", Red);
   if (ObjectFind("sAig2a") == -1) {
      ObjectCreate("sAig2a", OBJ_LABEL, 0, 0, 0);
      ObjectSet("sAig2a", OBJPROP_COLOR, Red);
      ObjectSet("sAig2a", OBJPROP_XDISTANCE, 5);
      ObjectSet("sAig2a", OBJPROP_YDISTANCE, 40);
   }
   ObjectSetText("sAig2a", "LAST BAR ANALYSIS: PENDING...", 10, "Tahoma Bold", White);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] > g_ibuf_104[1] && Close[1] < ld_16 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: UPTHRUST ON HIGH VOLUME", 10, "Tahoma Bold", Lime);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] > 2.0 * g_ibuf_104[1] && Close[1] < ld_16 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: UPTHRUST ON VERY HIGH VOLUME", 10, "Tahoma Bold", Lime);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] > g_ibuf_104[1] && Close[1] > 1.2 * ld_0 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: UPTHRUST ON HIGH VOLUME WITH CLOSE > MIDDLE", 10, "Tahoma Bold", Orange);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] > 2.0 * g_ibuf_104[1] && Close[1] > 1.2 * ld_0 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: UPTHRUST ON VERY HIGH VOLUME WITH CLOSE > MIDDLE", 10, "Tahoma Bold", Orange);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] < g_ibuf_104[1] && Close[1] < ld_16 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: PSEUDO UPTHRUST ON LOW VOLUME", 10, "Tahoma Bold", Lime);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] < g_ibuf_104[1] / 2.0 && Close[1] < ld_16 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: PSEUDO UPTHRUST ON VERY LOW VOLUME", 10, "Tahoma Bold", Lime);
   if (Close[1] > Close[2] && g_ibuf_84[1] < g_ibuf_92[1] / 2.0 && Close[1] <= ld_0 && g_ibuf_108[1] < g_ibuf_108[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: NO DEMAND / VOLUME SMALLER THAN PREVIOUS BAR", 10, "Tahoma Bold", Lime);
   if (Close[1] > Close[2] && g_ibuf_84[1] < g_ibuf_92[1] / 2.0 && Close[1] <= ld_0 && g_ibuf_108[1] > g_ibuf_104[1] && g_ibuf_108[1] < g_ibuf_108[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: SUPPLY IS SWAMPING THE DEMAND / HIGH VOLUME", 10, "Tahoma Bold", Lime);
   if (Close[1] > Close[2] && g_ibuf_84[1] < g_ibuf_92[1] / 2.0 && Close[1] <= ld_0 && g_ibuf_108[1] > 2.0 * g_ibuf_104[1] && g_ibuf_108[1] < g_ibuf_108[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: SUPPLY IS SWAMPING THE DEMAND / VERY HIGH VOLUME", 10, "Tahoma Bold", Lime);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && Close[1] > Close[2] && Close[1] > ld_8 && g_ibuf_108[1] > g_ibuf_108[2]) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: MARK UP BAR", 10, "Tahoma Bold", Lime);
   if (Close[1] < Close[2] && g_ibuf_108[1] > g_ibuf_104[1] && Close[1] > ld_8) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: STOPPING VOLUME / STRENGHT", 10, "Tahoma Bold", Lime);
   if (g_ibuf_108[1] > g_ibuf_104[1] && g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && Close[1] > Close[2] && Low[1] < Low[2] && Close[1] > ld_8) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: REVERSE UPTHRUST / STRENGHT", 10, "Tahoma Bold", Lime);
   if (g_ibuf_84[1] < g_ibuf_92[1] / 2.0 && g_ibuf_108[1] < g_ibuf_104[1] && Close[1] < Close[2] && Close[1] < ld_16) ObjectSetText("sAig2a", "LAST BAR ANALYSIS: NO SUPPLY / STRENGHT", 10, "Tahoma Bold", Lime);
   if (ObjectFind("1SIG") == -1) {
      ObjectCreate("1SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("1SIG", OBJPROP_COLOR, Red);
      ObjectSet("1SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("1SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("1SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] > g_ibuf_104[1] && Close[1] < ld_16 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("1SIG", "DESCRIPTION: WEAKNESS/mark down on high volume", 7, "Tahoma Bold", White);
   if (ObjectFind("2SIG") == -1) {
      ObjectCreate("2SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("2SIG", OBJPROP_COLOR, Red);
      ObjectSet("2SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("2SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("2SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] > 2.0 * g_ibuf_104[1] && Close[1] < ld_16 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("2SIG", "DESCRIPTION: Weakness/Mark down on very high volume", 7, "Tahoma Bold", White);
   if (ObjectFind("3SIG") == -1) {
      ObjectCreate("3SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("3SIG", OBJPROP_COLOR, Red);
      ObjectSet("3SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("3SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("3SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] > g_ibuf_104[1] && Close[1] > 1.2 * ld_0 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("3SIG", "DESCRIPTION: Not successful mark down/Too much demand.", 7, "Tahoma Bold", White);
   if (ObjectFind("4SIG") == -1) {
      ObjectCreate("4SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("4SIG", OBJPROP_COLOR, Red);
      ObjectSet("4SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("4SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("4SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] < g_ibuf_104[1] && Close[1] < ld_16 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("4SIG", "DESCRIPTION: Weakness/Not effective as the Upthrust.", 7, "Tahoma Bold", White);
   if (ObjectFind("5SIG") == -1) {
      ObjectCreate("5SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("5SIG", OBJPROP_COLOR, Red);
      ObjectSet("5SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("5SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("5SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && g_ibuf_108[1] < g_ibuf_104[1] && Close[1] < ld_16 && Close[1] > Close[2] && High[1] > High[2]) ObjectSetText("5SIG", "DESCRIPTION: Weakness/Not effective as the Upthrust.", 7, "Tahoma Bold", White);
   if (ObjectFind("6SIG") == -1) {
      ObjectCreate("6SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("6SIG", OBJPROP_COLOR, Red);
      ObjectSet("6SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("6SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("6SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (Close[1] > Close[2] && g_ibuf_84[1] < g_ibuf_92[1] / 2.0 && Close[1] <= ld_0 && g_ibuf_108[1] < g_ibuf_108[2]) ObjectSetText("6SIG", "DESCRIPTION: Weakness/No support/Lack of participation from SM.", 7, "Tahoma Bold", White);
   if (ObjectFind("7SIG") == -1) {
      ObjectCreate("7SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("7SIG", OBJPROP_COLOR, Red);
      ObjectSet("7SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("7SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("7SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (Close[1] > Close[2] && g_ibuf_84[1] < g_ibuf_92[1] / 2.0 && Close[1] <= ld_0 && g_ibuf_108[1] > g_ibuf_104[1] && g_ibuf_108[1] < g_ibuf_108[2]) ObjectSetText("7SIG", "DESCRIPTION: Next bars indicates whether the supply is persisting or not.", 7, "Tahoma Bold", White);
   if (ObjectFind("8SIG") == -1) {
      ObjectCreate("8SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("8SIG", OBJPROP_COLOR, Red);
      ObjectSet("8SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("8SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("8SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && Close[1] > Close[2] && Close[1] > ld_8 && g_ibuf_108[1] > g_ibuf_108[2]) ObjectSetText("8SIG", "DESCRIPTION: Effort to move prices up/Potential weakness", 7, "Tahoma Bold", White);
   if (ObjectFind("9SIG") == -1) {
      ObjectCreate("9SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("9SIG", OBJPROP_COLOR, Red);
      ObjectSet("9SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("9SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("9SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (Close[1] < Close[2] && g_ibuf_108[1] > g_ibuf_104[1] && Close[1] > ld_8) ObjectSetText("9SIG", "DESCRIPTION: Strenght/Accumulation/Reversal of down trend", 7, "Tahoma Bold", White);
   if (ObjectFind("10SIG") == -1) {
      ObjectCreate("10SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("10SIG", OBJPROP_COLOR, Red);
      ObjectSet("10SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("10SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("10SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (g_ibuf_108[1] > g_ibuf_104[1] && g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && Close[1] > Close[2] && Low[1] < Low[2] && Close[1] > ld_8) ObjectSetText("10SIG", "DESCRIPTION: Strenght/Immediate Reversal", 7, "Tahoma Bold", White);
   if (ObjectFind("11SIG") == -1) {
      ObjectCreate("11SIG", OBJ_LABEL, 0, 0, 0);
      ObjectSet("11SIG", OBJPROP_COLOR, Red);
      ObjectSet("11SIG", OBJPROP_XDISTANCE, 5);
      ObjectSet("11SIG", OBJPROP_YDISTANCE, 58);
   }
   ObjectSetText("11SIG", "DESCRIPTION: ", 7, "Tahoma Bold", White);
   if (g_ibuf_108[1] > g_ibuf_104[1] && g_ibuf_84[1] > 1.5 * g_ibuf_92[1] && Close[1] > Close[2] && Low[1] < Low[2] && Close[1] > ld_8) ObjectSetText("11SIG", "DESCRIPTION: Strenght/In down moves means reversal/In up moves continuation", 7, "Tahoma Bold", White);
}