/*
   Generated by ex4-to-mq4 decompiler FREEWARE 4.0.451.5
   Website: h TT p : / / WwW .MeTa Q U oT e S .N ET
   E-mail : sUpp or T@ m E TaQ u oT E S . Ne T
*/
#property copyright "Copyright © 2008, FOREXflash Software Corp."
#property link      "http://www.metaquotes.net"

#property indicator_chart_window

extern int LinesAboveBelow = 150;
int Gi_80 = 0;
int Gi_84 = 0;

int init() {
   string Ls_0 = "2030.06.12";
   int str2time_8 = StrToTime(Ls_0);
   if (TimeCurrent() >= str2time_8) {
      Alert("The trial version expired! Contact forexflash@gmail.com");
      return (1);
   }
   return (0);
}

int deinit() {
   string name_8;
   int Li_0 = ObjectsTotal();
   for (int objs_total_4 = Li_0; objs_total_4 >= 0; objs_total_4--) {
      name_8 = ObjectName(objs_total_4);
      if (StringSubstr(name_8, 0, 11) == "[SweetSpot]") ObjectDelete(name_8);
   }
   return (0);
}

int start() {
   int Li_24;
   double Ld_28;
   string Ls_0 = "2030.06.12";
   int str2time_8 = StrToTime(Ls_0);
   if (TimeCurrent() >= str2time_8) {
      Alert("The trial version expired! Contact forexflash@gmail.com");
      return (1);
   }
   if (TimeCurrent() - Gi_80 < 600 && Period() == Gi_84) return (0);
   int Li_16 = Bid / Point;
   Li_16 -= Li_16 % 1000;
   for (int Li_12 = -LinesAboveBelow; Li_12 < LinesAboveBelow; Li_12++) {
      Li_24 = Li_16 + 1000 * Li_12;
      if (Li_24 % 1000 == 0) {
      }
      Ld_28 = Li_24 * Point;
      drawLine(DoubleToStr(Ld_28, Digits), Time[1], Time[0], Ld_28, Ld_28, 1, FALSE, Orange, 1);
   }
   return (0);
}

void drawLine(string A_name_0, int A_datetime_8, int A_datetime_12, double A_price_16, double A_price_24, int A_width_32, int A_bool_36, color A_color_40, int Ai_44) {
   if (ObjectFind(A_name_0) != 0) {
      ObjectCreate(A_name_0, OBJ_TREND, 0, A_datetime_8, A_price_16, A_datetime_12, A_price_24);
      if (Ai_44 == 1) ObjectSet(A_name_0, OBJPROP_STYLE, STYLE_SOLID);
      else {
         if (Ai_44 == 2) ObjectSet(A_name_0, OBJPROP_STYLE, STYLE_DASHDOT);
         else ObjectSet(A_name_0, OBJPROP_STYLE, STYLE_DOT);
      }
      ObjectSet(A_name_0, OBJPROP_COLOR, A_color_40);
      ObjectSet(A_name_0, OBJPROP_WIDTH, A_width_32);
      ObjectSet(A_name_0, OBJPROP_RAY, A_bool_36);
      return;
   }
   ObjectDelete(A_name_0);
   ObjectCreate(A_name_0, OBJ_TREND, 0, A_datetime_8, A_price_16, A_datetime_12, A_price_24);
   if (Ai_44 == 1) ObjectSet(A_name_0, OBJPROP_STYLE, STYLE_SOLID);
   else {
      if (Ai_44 == 2) ObjectSet(A_name_0, OBJPROP_STYLE, STYLE_DASHDOT);
      else ObjectSet(A_name_0, OBJPROP_STYLE, STYLE_DOT);
   }
   ObjectSet(A_name_0, OBJPROP_COLOR, A_color_40);
   ObjectSet(A_name_0, OBJPROP_WIDTH, A_width_32);
   ObjectSet(A_name_0, OBJPROP_RAY, A_bool_36);
}